shopproject/cart/urls.py
from . import views
from django.urls import path


app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.remove, name='remove'),
    path('delete/<int:product_id>/',views.delete,name='delete'),
]

shopproject/myapp/urls.py
from . import views
from django.urls import path


app_name='myapp'
urlpatterns = [

    path('',views.allProduct,name='allProduct'),
    path('<slug:c_slug>/',views.allProduct,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productDetail,name='productDetail')
]

shopproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopproject/search/urls.py
from . import views
from django.urls import path


app_name='search'
urlpatterns = [

    path('',views.searchResult,name='searchResult'),

]

shopproject/cart/models.py
from django.db import models
from myapp.models import Product
# Create your models here.



class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shopproject/myapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('myapp:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='product',blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('myapp:productDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

shopproject/search/models.py
from django.db import models

# Create your models here.

shopproject/cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from myapp.models import Product
from .models import Cart,CartItem
# Create your views here.


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.session_create()
    return cart

def add_cart(request, product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
    cart.save()

    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,counter=0,total=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(counter=counter,total=total,cart_items=cart_items))

def remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def delete(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

shopproject/myapp/views.py
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render, get_object_or_404
from .models import Category,Product

# Create your views here.


def allProduct(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,'3')
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1

    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})


def productDetail(request,product_slug,c_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

shopproject/search/views.py
from django.shortcuts import render
from myapp.models import Product
from django.db.models import Q
# Create your views here.



def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)|Q(desc__contains=query))

    return render(request,'search.html',{'products':products,'query':query})

shopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    {% include 'head.html' %}
    {% include 'navbar.html' %}
    {% block content %} {% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    This is cart page

{% endblock %}
{% block title %}

    Cart - ABC Cafe

{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <h1>Your Cart is Empty</h1>
            <br>
            <p>click<a href="{% url 'myapp:allProduct' %}"> Here </a>to continue shopping</p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center">
            <h2>Your Shopping Cart</h2>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center">
                <table class="table">
                    <thead class="cart_tb">
                    <tr>
                        <th colspan="5">Your  Items</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.img.url}}" alt="#" class="float-left cart_img"></a>
                        </td>
                        <td class="text-left">
                            <p>
                                NAME: {{cart_item.product.name}}<br>
                                SKU: {{cart_item.product.id}}<br>
                                PRICE: ${{cart_item.product.price}}<br>
                                Qty: {{cart_item.quantity}} X ${{cart_item.product.price}}<br>
                            </p>
                        </td>
                        <td>
                            Total: ${{cart_item.sub_total}}
                        </td>
                        {% if cart_item.product.stock > cart_item.quantity %}
                        <td>
                            <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa-solid fa-plus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                        </td>
                        {% else %}
                        <td>
                            &nbsp;<a href="{% url 'cart:remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 text-center">
                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            Check Out
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th>
                            Please review your shopping cart items before proceeding with the order payment
                        </th>
                    </tr>
                    <tr>
                        <td>
                            Your total:<b>{{total}}</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a class="btn btn-secondary" href="{% url 'myapp:allProduct' %}">continue shopping</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{category.desc | truncatewords:155}}
{% else %}
    welcome to our cafe
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
    {{category.name}} - ABC Cafe
{% else %}
    See our Menu - ABC Cafe
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
    <img class="pd_img" src="{{category.img.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h2 class="text-center">{{category.name}}</h2>
    <p>{{category.desc}}</p>
</div>
{% else %}
<div>
    <img class="banner" src="{% static 'img/banner.png' %}" alt="banner.img">
</div>
<br>
<div>
    <h2 class="main_head text-center">Our Menu List</h2>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English</p>
</div>
{% endif %}
<div class="container">
    <div class="row">
        {% for product in products.object_list %}
        <div class="col-md-4">
            <div class="card p-3 shadow text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="cat_img" src="{{product.img.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <p>{{product.price}}</p>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
</div>
<br>
<div class="container">
    <div class="row mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {%  for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
<br>
{% endblock %}

shopproject/templates/footer.html
<div class="container-fluid text-center footer">
    &copy; ABC pvt ltd Kochi
</div>

shopproject/templates/head.html
{% load static %}
<header>
    <center>
        <a href="{% url 'myapp:allProduct' %}"><img class="logo" src="{% static 'img/logo.png' %}" alt="logoimg"></a>
    </center>
</header>

shopproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'myapp:allProduct' %}">All Products</a></li>
              {% for i in links %}
                <li><a class="dropdown-item" href="{{i.get_url}}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search:searchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.desc}}

{% endblock %}
{% block title %}

    {{product.name}} - ABC Cafe

{% endblock %}
{% block content %}
<div class="container">
    <div class="row mx-auto">
        <p class="bar"><a href="{% url 'myapp:allProduct' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="pdt_img" src="{{product.img.url}}" alt="{{product.name}]">
        </div>

        <div class="col-md-6">
            <div>
                <h2>{{product.name}}</h2>
                <p>${{product.price}}</p>
                <h4>{{product.desc}}</h4>
            </div>
            <br>
            <div>
                {% if product.stock == 0 %}
                    <h3><b>Out of Stock</b></h3>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
 <br>
{% endblock %}

shopproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have different variety of drinks

{% endblock %}
{% block title %}
    Search Result -ABC Cafe

{% endblock %}
{% block content %}
<div>
    <div>
        <p class="text-center">
            You are searched for:<b>{{query}}</b>
        </p>
    </div>
    <br>
    <div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <div class="card p-3 shadow text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="cat_img" src="{{product.img.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <p>{{product.price}}</p>
                </div>
            </div>
            <br>
        </div>
        <br>
        {% empty %}
        <div class="mx-auto">
            <p class="text-center"> 0 Result founded</p>
        </div>
        {% endfor %}
    </div>
</div>
</div>
<br>
{% endblock %}